### ISSUE TITLE
OAS(OpenApi Specification)のyamlからSwaggerを起動できるようにする

### ISSUE THREAD

**Issue by unvavo** [sakaba-project/sakaba#29]
https://github.com/sakaba-project/sakaba/issues/11
と被ってるかも

**Comment by shamisonn** [comment]
#11 はwikiに書くけど、OASの場合はコードで表現するってことだろうからいいと思う！
OAS好き！！いいね！！！

**Comment by shamisonn** [comment]
Goalはmakeかshellかなんかしからでコマンドでswaggerを起動させるような機構を実装する

**Comment by shamisonn** [comment]
ライブラリ
- https://github.com/swaggo/gin-swagger
- https://github.com/swaggo/swag
ここらへんがりようできる？かも
