### ISSUE TITLE
テストのルール作成

### ISSUE THREAD

**Issue by ghost** [sakaba-project/sakaba#33]
テストをだれがいつどのタイミングで書くのかを決める

=> 実装と一緒にテストをセットで書くをドキュメント化する

**Comment by shamisonn** [comment]
https://github.com/sakaba-project/sakaba/wiki/%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E6%9B%B8%E3%81%8F%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%B3%E3%82%B0
に書いた。ちょっと内容変えたいところあるので、slackにて軽くレビューもらう
