### ISSUE TITLE
Userの認証周りについてどうやって実現するか考えてみる

### ISSUE THREAD

**Issue by shamisonn** [sakaba-project/sakaba#42]
- [x] scopeを決める
  - ログイン、ログアウト部分の認証方式を考える
  - アカウント登録/登録解除は必要か？を考える
  - アカウント作成をどうやるか、は後で必要になったら考える
- [x] how
  - 認証方式
    - jwtとか
    - cf. https://qiita.com/uasi/items/cfb60588daa18c2ec6f5

**Comment by ghost** [comment]
セッション認証系のいいライブラリ見つからないし

https://github.com/dgrijalva/jwt-go
jwtでいいような気がしてきた

せっかくだしこの辺確認しながら進めたい
https://techracho.bpsinc.jp/hachi8833/2019_10_09/80851
とはいえ、JSの話だとcookieも危ない気がしているのでこの話もう少しちゃんと調べたい

あと認証の話とはあまり関係ないけどspaだとこの辺も気にしないといけないのかな
https://developer.mozilla.org/ja/docs/Web/HTTP/CORS

**Comment by ghost** [comment]
ベストプラクティ的には
認証サーバー切り離した方がようさそうだが、
そこまでやらなくていい気がしているので
同一サーバーでやってしまって
認証のapi作る
認可はmiddleware層を作ってそこでやってしまうのでいい感じがする
